version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    labels:
      - type/dependencies
    groups:
      minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - type/dependencies
    groups:
      minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: weekly
    labels:
      - component/core
      - type/dependencies
    groups:
      minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /eml-client/
    schedule:
      interval: weekly
    labels:
      - component/client
      - type/dependencies
    groups:
      minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: terraform
    directory: /lambda-smtp-relay/
    schedule:
      interval: weekly
    labels:
      - component/lambda-smtp-relay
      - type/dependencies
    groups:
      minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: terraform
    directory: /outgoing/
    schedule:
      interval: weekly
    labels:
      - component/outgoing
      - type/dependencies
    groups:
      minor:
        update-types:
          - minor
          - patch
