name: build

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  tauri-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          submodules: recursive

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: .node-version
          cache: yarn
          cache-dependency-path: eml-client/yarn.lock

      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1 (stable)

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            just \
            libnotmuch-dev
          # Tauri Linux prerequisites from https://v2.tauri.app/start/prerequisites/#linux
          sudo apt-get install -y \
            build-essential \
            curl \
            file \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libssl-dev \
            libwebkit2gtk-4.1-dev \
            wget

      - name: Install tauri CLI
        run: cargo install tauri-cli --locked --version '^2.0.0'

      - name: Install frontend dependencies
        working-directory: eml-client
        run: yarn install --frozen-lockfile

      - name: Build Tauri app
        env:
          JUST_UNSTABLE: "1"
        run: just build-debug

      - name: Upload built app
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: amail-tauri-linux-debug-${{ github.sha }}
          path: target/debug/amail
          if-no-files-found: error
