name: build

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  tauri-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: eml-client/yarn.lock

      - uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            just \
            libnotmuch-dev
          # Tauri Linux prerequisites from https://v2.tauri.app/start/prerequisites/#linux
          sudo apt-get install -y \
            build-essential \
            curl \
            file \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libssl-dev \
            libwebkit2gtk-4.1-dev \
            wget

      - name: Install tauri CLI
        run: cargo install tauri-cli --locked --version '^2.0.0'

      - name: Install frontend dependencies
        working-directory: eml-client
        run: yarn install --frozen-lockfile

      - name: Build Tauri app
        run: just build-debug

      - name: Upload built app
        uses: actions/upload-artifact@v4
        with:
          name: amail-tauri-linux-debug-${{ github.sha }}
          path: target/debug/amail
          if-no-files-found: error
