name: pre-commit

on:
  push:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          submodules: recursive

      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          check-latest: true

      - name: Install pre-commit
        run: python -m pip install pre-commit

      - name: Set up pre-commit
        run: pre-commit install --install-hooks

      - name: Set up terraform
        uses: OJFord/tenv-github-action@edaa7e549acbacd4d6fbf5abac73af87edee2210 # main
        with:
          tool_name: terraform

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y libnotmuch-dev
          sudo apt-get install -y just
          # Tauri pre-reqs
          sudo apt-get install -y libwebkit2gtk-4.1-dev

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
